AWSTemplateFormatVersion: '2010-09-09'
Description: Create VPC and subnets (public, protected, private) in 1 AZ.

# ==================== Parameters ====================
Parameters:
  SystemName:
    Type: String
    Default: techpit

  EnvironmentName:
    Type: String
    Default: dev

  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetAz1Cidr:
    Type: String
    Default: 10.0.0.0/24

  ProtectedSubnetAz1Cidr:
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnetAz1Cidr:
    Type: String
    Default: 10.0.2.0/24

  PublicSubnetAz2Cidr:
    Type: String
    Default: 10.0.100.0/24

  ProtectedSubnetAz2Cidr:
    Type: String
    Default: 10.0.101.0/24

  PrivateSubnetAz2Cidr:
    Type: String
    Default: 10.0.102.0/24

  PublicSubnetAz3Cidr:
    Type: String
    Default: 10.0.200.0/24

  ProtectedSubnetAz3Cidr:
    Type: String
    Default: 10.0.201.0/24

  PrivateSubnetAz3Cidr:
    Type: String
    Default: 10.0.202.0/24

  Az1:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a

  Az2:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1c

  Az3:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1d

# ==================== Resources ====================
Resources:
  # -------------------- VPC --------------------
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-vpc'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # -------------------- Internet Gateway --------------------
  # IGW
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-igw'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # attachment
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # -------------------- Subnets --------------------
  # Public Subnet AZ1
  PublicSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az1
      CidrBlock: !Ref PublicSubnetAz1Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-public-az1'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Public Subnet AZ2
  PublicSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az2
      CidrBlock: !Ref PublicSubnetAz2Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-public-az2'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Public Subnet AZ3
  PublicSubnetAz3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az3
      CidrBlock: !Ref PublicSubnetAz3Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-public-az3'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Protected Subnet AZ1
  ProtectedSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az1
      CidrBlock: !Ref ProtectedSubnetAz1Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-protected-az1'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Protected Subnet AZ2
  ProtectedSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az2
      CidrBlock: !Ref ProtectedSubnetAz2Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-protected-az2'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Protected Subnet AZ3
  ProtectedSubnetAz3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az3
      CidrBlock: !Ref ProtectedSubnetAz3Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-protected-az3'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Private Subnet AZ1
  PrivateSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az1
      CidrBlock: !Ref PrivateSubnetAz1Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-private-az1'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Private Subnet AZ2
  PrivateSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az2
      CidrBlock: !Ref PrivateSubnetAz2Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-private-az2'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Private Subnet AZ3
  PrivateSubnetAz3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref Az3
      CidrBlock: !Ref PrivateSubnetAz3Cidr
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-subnet-private-az3'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # -------------------- Route Tables --------------------
  # Public
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-rtb-public'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Protected AZ1
  ProtectedRouteTableAz1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-rtb-protected-az1'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Protected AZ2
  ProtectedRouteTableAz2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-rtb-protected-az2'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Protected AZ3
  ProtectedRouteTableAz3:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-rtb-protected-az3'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # Private
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-rtb-private'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # -------------------- Routes --------------------
  # Public Route
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable

  # Protected Route AZ1
  ProtectedRouteAz1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProtectedRouteTableAz1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayAz1

  # Protected Route AZ2
  ProtectedRouteAz2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProtectedRouteTableAz2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayAz2

  # Protected Route AZ3
  ProtectedRouteAz3:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProtectedRouteTableAz3
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayAz3

  # -------------------- SubnetRouteTableAssociation --------------------
  # Public AZ1
  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAz1
      RouteTableId: !Ref PublicRouteTable

  # Public AZ2
  PublicRouteTableAssociationAz2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAz2
      RouteTableId: !Ref PublicRouteTable

  # Public AZ3
  PublicRouteTableAssociationAz3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAz3
      RouteTableId: !Ref PublicRouteTable

  # Protected AZ1
  ProtectedRouteTableAssociationAz1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProtectedSubnetAz1
      RouteTableId: !Ref ProtectedRouteTableAz1

  # Protected AZ2
  ProtectedRouteTableAssociationAz2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProtectedSubnetAz2
      RouteTableId: !Ref ProtectedRouteTableAz2

  # Protected AZ3
  ProtectedRouteTableAssociationAz3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProtectedSubnetAz3
      RouteTableId: !Ref ProtectedRouteTableAz3

  # Private AZ1
  PrivateRouteTableAssociationAz1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetAz1
      RouteTableId: !Ref PrivateRouteTable

  # Private AZ2
  PrivateRouteTableAssociationAz2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetAz2
      RouteTableId: !Ref PrivateRouteTable

  # Private AZ3
  PrivateRouteTableAssociationAz3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetAz3
      RouteTableId: !Ref PrivateRouteTable

  # -------------------- NAT Gateway --------------------
  # EIP
  EipNatAz1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-eip-az1'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  EipNatAz2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-eip-az2'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  EipNatAz3:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-eip-az3'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  # NAT Gateway
  NatGatewayAz1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EipNatAz1.AllocationId
      SubnetId: !Ref PublicSubnetAz1
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-nat-az1'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  NatGatewayAz2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EipNatAz2.AllocationId
      SubnetId: !Ref PublicSubnetAz2
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-nat-az2'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName

  NatGatewayAz3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EipNatAz3.AllocationId
      SubnetId: !Ref PublicSubnetAz3
      Tags:
        - Key: Name
          Value: !Sub '${SystemName}-${EnvironmentName}-nat-az3'
        - Key: System
          Value: !Ref SystemName
        - Key: Environment
          Value: !Ref EnvironmentName
